blank_issues_enabled: false
contact_links:
  - name: ğŸ§ p5.sound Issues
    url: https://github.com/processing/p5.js-sound/issues
    about: Report issues with p5.sound here.
  - name: ğŸŒ Website Issues
    url: https://github.com/processing/p5.js-website/issues
    about: Report issues with the p5.js website here.
  - name: ğŸ–¥ï¸ Web Editor Issues
    url: https://github.com/processing/p5.js-web-editor/issues
    about: Report issues with the p5.js web editor here.
  - name: ğŸ’¬ Forum
    url: https://discourse.processing.org/c/p5js
    about: Have other questions about using p5.js? Ask them here!
  
