name: Generate Contributors PNG

on:
  push:
    paths:
      - '.all-contributorsrc'

jobs:
  build:
    if: github.ref == 'refs/heads/main' && github.repository == 'processing/p5.js'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system deps for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            libjpeg-dev

      - name: Install dependencies
        run: npm install canvas node-fetch

      - name: Run contributors-svg generator
        run: node utils/contributors-png.js

      - name: Reset all changes except contributors.png
        run: |
          git restore --staged .
          git add contributors.svg
          git checkout -- .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update contributors.png from .all-contributorsrc"
          branch: update-contributors-svg
          title: "chore: update contributors.png from .all-contributorsrc"
          body: "This PR updates the contributors.png to reflect changes in .all-contributorsrc"
          add-paths: contributors.svg
          token: ${{ secrets.ACCESS_TOKEN }}
